name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate static site
      run: |
        mkdir site
        # Copiar todos os arquivos e pastas do repositório para a pasta 'site'
        rsync -av --exclude='site' ./ site/
        # Gerar o index.html básico
        echo "<html><body><h1>Arquivos do Repositório</h1><ul>" > site/index.html
        find . -type f ! -path "./site/*" | sed 's|^\./||' | while read file; do
          echo "<li><a href=\"$file\">$file</a></li>" >> site/index.html
        done
        echo "</ul></body></html>" >> site/index.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site